apps/urls.py
from django.urls import path
from .models import *
from .views import kepsekView as kepsekViews
from .views import guruView as guruViews
from .views import produkView as produkViews
from .views import teknisiView as teknisiViews
from .views import salesView as salesViews
from .views import sptteknisiView as sptteknisiViews
from .views import sptprodukView as sptprodukViews
from .views import sptsalesView as sptsalesViews
from .views import mainViews as mainViews

urlpatterns = [
    # Kepsek
    path("kepsek/", kepsekViews.index, name="kepsek"),
    path("kepsek/komplain/", kepsekViews.komplain, name="komplain_kepsek"),
    path("kepsek/permintaan/", kepsekViews.permintaan, name="permintaan_kepsek"),
    path("kepsek/saran/", kepsekViews.saran, name="saran_kepsek"),

    # Guru
    path("guru/", guruViews.index, name="guru"),
    path("guru/komplain/", guruViews.komplain, name="komplain_guru"),
    path("guru/permintaan/", guruViews.permintaan, name="permintaan_guru"),
    path("guru/saran/", guruViews.saran, name="saran_guru"),

    # Produk
    path("produk/", produkViews.index, name="produk"),
    path("produk/komplain/", produkViews.komplain, name="komplain_produk"),
    path("produk/permintaan/", produkViews.permintaan, name="permintaan_produk"),
    path("produk/saran/", produkViews.saran, name="saran_produk"),
    path("produk/sptpermintaan/", produkViews.sptpermintaan, name="sptpermintaan_produk"),
    path("produk/pengumuman/", produkViews.pengumuman, name="pengumuman_produk"),
    path("produk/kunjungan_tik/", produkViews.kunjungan_tik, name="kunjungan_produk_tik"),
    path("produk/kunjungan_ekskul/", produkViews.kunjungan_ekskul, name="kunjungan_produk_ekskul"),
    path("produk/jadwal/", produkViews.jadwal, name="jadwal_produk"),
    path("produk/pengeluaran/", produkViews.pengeluaran, name="pengeluaran_produk"),

    # Teknisi
    path("teknisi/", teknisiViews.index, name="teknisi"),
    path("teknisi/komplain/", teknisiViews.komplain, name="komplain_teknisi"),
    path("teknisi/permintaan/", teknisiViews.permintaan, name="permintaan_teknisi"),
    path("teknisi/saran/", teknisiViews.saran, name="saran_teknisi"),
    path("teknisi/sptpermintaan/", teknisiViews.sptpermintaan, name="sptpermintaan_teknisi"),
    path("teknisi/pengumuman/", teknisiViews.pengumuman, name="pengumuman_teknisi"),
    path("teknisi/kunjungan/", teknisiViews.kunjungan, name="kunjungan_teknisi"),
    path("teknisi/pengeluaran/", teknisiViews.pengeluaran, name="pengeluaran_teknisi"),
    
    # Sales
    path("sales/", salesViews.index, name="sales"),
    path("sales/jadwal/", salesViews.jadwal, name="jadwal_sales"),
    path("sales/sptpermintaan/", salesViews.sptpermintaan, name="sptpermintaan_sales"),
    path("sales/pengumuman/", salesViews.pengumuman, name="pengumuman_sales"),
    path("sales/pengeluaran/", salesViews.pengeluaran, name="pengeluaran_sales"),
    
    # SPT Teknisi
    path("spt/teknisi/", sptteknisiViews.index, name="sptteknisi"),
    path("spt/teknisi/komplain/", sptteknisiViews.komplain, name="komplain_sptteknisi"),
    path("spt/teknisi/permintaan/", sptteknisiViews.permintaan, name="permintaan_sptteknisi"),
    path("spt/teknisi/saran/", sptteknisiViews.saran, name="saran_sptteknisi"),
    path("spt/teknisi/sptpermintaan/", sptteknisiViews.sptpermintaan, name="sptpermintaan_sptteknisi"),
    path("spt/teknisi/pengumuman/", sptteknisiViews.pengumuman, name="pengumuman_sptteknisi"),
    path("spt/teknisi/customer/", sptteknisiViews.customer, name="customer_sptteknisi"),
    path("spt/teknisi/customer_ekskul/", sptteknisiViews.customer_ekskul, name="customer_ekskul_sptteknisi"),
    path("spt/teknisi/pengeluaran/", sptteknisiViews.pengeluaran, name="pengeluaran_sptteknisi"),
    # SPT Produk
    path("spt/produk/", sptprodukViews.index, name="sptproduk"),
    path("spt/produk/komplain/", sptprodukViews.komplain, name="komplain_sptproduk"),
    path("spt/produk/permintaan/", sptprodukViews.permintaan, name="permintaan_sptproduk"),
    path("spt/produk/saran/", sptprodukViews.saran, name="saran_sptproduk"),
    path("spt/produk/sptpermintaan/", sptprodukViews.sptpermintaan, name="sptpermintaan_sptproduk"),
    path("spt/produk/pengumuman/", sptprodukViews.pengumuman, name="pengumuman_sptproduk"),
    path("spt/produk/karyawan/", sptprodukViews.karyawan, name="karyawan_sptproduk"),
    path("spt/produk/penggajian/", sptprodukViews.penggajian, name="penggajian_sptproduk"),
    path("spt/produk/customer/", sptprodukViews.customer, name="customer_sptproduk"),
    path("spt/produk/customer_ekskul/", sptprodukViews.customer_ekskul, name="customer_ekskul_sptproduk"),
    path("spt/produk/pengeluaran/", sptprodukViews.pengeluaran, name="pengeluaran_sptproduk"),
    
    # SPT Sales
    path("spt/sales/", sptsalesViews.index, name="sptsales"),
    path("spt/sales/sptpermintaan/", sptsalesViews.sptpermintaan, name="sptpermintaan_sptsales"),
    path("spt/sales/pengumuman/", sptsalesViews.pengumuman, name="pengumuman_sptsales"),
    path("spt/sales/customer/", sptsalesViews.customer, name="customer_sptsales"),
    path("spt/sales/pembayaran/", sptsalesViews.pembayaran, name="pembayaran_sptsales"),
    path("spt/sales/adendum/", sptsalesViews.adendum, name="adendum_sptsales"),
    path("spt/sales/adendum_ekskul/", sptsalesViews.adendum_ekskul, name="adendum_ekskul_sptsales"),
    path("spt/sales/customer_ekskul/", sptsalesViews.customer_ekskul, name="customer_ekskul_sptsales"),
    path("spt/sales/pengeluaran/", sptsalesViews.pengeluaran, name="pengeluaran_sptsales"),

     
    # Main
    path("", mainViews.index, name="index"),
    path("login/", mainViews.login_view, name="login"),
    path("logout/", mainViews.logout_view, name="logout"),
    path("testing/", mainViews.testing, name="testing"),
    path("cetak/produk/", mainViews.cetak_produk, name="cetak_produk"),
    path("cetak/teknisi/", mainViews.cetak_teknisi, name="cetak_teknisi"),
    path("cetak/ekskul/", mainViews.cetak_ekskul, name="cetak_ekskul"),
    path("cetak/produk/", mainViews.cetak_produk, name="cetak_produk"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from apps.views.mainViews import PengumumanViewSet, CustomerViewSet, CustomerDetailViewSet, MasterEkstrakulikulerViewSet, MasterEkstrakulikulerDetailViewSet
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
    path('api/pengumuman/', PengumumanViewSet.as_view(), name='pengumuman-list'),
    path('api/customer/', CustomerViewSet.as_view(), name='customer-list'),
    path('api/customer/<int:pk>/', CustomerDetailViewSet.as_view(), name='customer-detail'),
    path('api/ekstrakulikuler/', MasterEkstrakulikulerViewSet.as_view(), name='ekstrakulikuler-list'),
    path('api/ekstrakulikuler/<int:pk>/', MasterEkstrakulikulerDetailViewSet.as_view(), name='ekstrakulikuler-detail'),
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

apps/models/kspModel.py
from django.contrib.auth.models import User
from django.db import models
from .mainModel import master

KATEGORI_CHOICES = [
  ("produk", "Produk"), 
  ("teknisi", "Teknisi")
]

STATUS_CHOICES = [
    ("menunggu", "Menunggu"),
    ("diterima", "Diterima"),
]

class komplain(models.Model):
    judul = models.CharField(max_length=255)
    keterangan = models.CharField(max_length=255)
    kategori = models.CharField(max_length=255, choices=KATEGORI_CHOICES)
    tanggal = models.DateField(max_length=255)
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default="menunggu")
    file = models.FileField(upload_to="komplain/", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="komplain")
    sekolah = models.ForeignKey(master, on_delete=models.CASCADE, related_name="komplain", null=True, blank=True)

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "komplain"


class saran(models.Model):
    judul = models.CharField(max_length=255)
    keterangan = models.CharField(max_length=255)
    kategori = models.CharField(max_length=255, choices=KATEGORI_CHOICES)
    tanggal = models.DateField(max_length=255)
    file = models.FileField(upload_to="saran/", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="saran")
    sekolah = models.ForeignKey(master, on_delete=models.CASCADE, related_name="saran")
    

    def __str__(self):
        return self.judul
    class Meta:
        verbose_name_plural = "saran"



class permintaan(models.Model):
    judul = models.CharField(max_length=255)
    keterangan = models.CharField(max_length=255)
    kategori = models.CharField(max_length=255, choices=KATEGORI_CHOICES)
    tanggal = models.DateField(max_length=255)
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default="menunggu")
    file = models.FileField(upload_to="permintaan/", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="permintaan")
    sekolah = models.ForeignKey(master, on_delete=models.CASCADE, related_name="permintaan")

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "permintaan"

templates/cetak/produk.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Form Supervisi</title>
{% endblock %}

{% block head %}
    <meta name="author" content="Diginusa">
    <meta name="description" content="Form Supervisi">
    <meta name="keywords" content="Form Supervisi">
    <link rel="icon" href="{% static 'images/logo.png' %}">
    <style>
        @page {
            size: A4;
            margin: 0;
        }
        @media print {
            body {
                width: 210mm;
                height: 297mm;
            }
            .no-print {
                display: none !important;
            }
        }
    </style>
{% endblock %}

{% block content %}
    <div class="bg-white dark:bg-gray-900 text-gray-900 dark:text-white p-8">
        <div class="max-w-4xl mx-auto">
            <div class="flex flex-col items-start mb-8">
                <img src="{% static 'images/DiginusaLogo.png' %}" alt="Logo Perusahaan" class="w-40 mb-4">
                <h1 class="text-3xl font-bold">Form Supervisi</h1>
            </div>

            <hr class="my-8 border-1.5 border-black dark:border-white">

            <div class="space-y-4 mb-8">
                <p><span class="font-semibold">Nama PIC:</span> {{ kunjungan.produk.nama }}</p>
                {% if kunjungan.sekolah %}
                    <p><span class="font-semibold">Nama Sekolah:</span> {{ kunjungan.sekolah.nama_sekolah }}</p>
                    <p><span class="font-semibold">Jenjang:</span> {{ kunjungan.sekolah.jenjang }}</p>
                {% else %}
                    <p><span class="font-semibold">Nama Sekolah:</span> {{ kunjungan.sekolah_ekskul.nama_sekolah }}</p>
                    <p><span class="font-semibold">Jenjang:</span> {{ kunjungan.sekolah_ekskul.jenjang }}</p>
                {% endif %}
                <p><span class="font-semibold">Tanggal:</span> {{ kunjungan.tanggal }}</p>
            </div>

            <hr class="my-8 border-1.5 border-black dark:border-white">

            <div class="mb-8">
                <h2 class="text-xl font-semibold mb-4">Layanan Supervisi:</h2>
                <p class="whitespace-pre-line">{{ kunjungan.deskripsi }}</p>
            </div>
            {% if kunjungan.ttd %}
            <div class="mt-16 flex justify-end">
                <div class="flex flex-col items-center justify-center max-w-[200px] w-full">
                    <img src="{{ kunjungan.ttd.url }}" alt="Tanda Tangan" class="mb-4 max-w-[200px]">
                    <hr class="w-full border-1 border-black dark:border-white mb-4">
                    <div class="flex flex-col items-center">
                        <p class="font-semibold text-center">{{ kunjungan.nama_kepsek_atau_guru }}</p>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="mt-16 flex justify-end">
                <div class="flex flex-col items-center justify-center max-w-[200px] w-full">
                    <p class="mb-4 text-center">Dikontak</p>
                </div>
            </div>
            {% endif %}

            <div class="mt-8 flex justify-center gap-4">
                <button class="no-print px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50" onclick="window.print()">Cetak</button>
                <button onclick="window.history.back()" class="no-print px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-opacity-50">Kembali</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/cetak/teknisi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Layanan Teknisi</title>
{% endblock %}

{% block head %}
    <meta name="author" content="Diginusa">
    <meta name="description" content="Layanan Teknisi">
    <meta name="keywords" content="Layanan Teknisi">
    <link rel="icon" href="{% static 'images/logo.png' %}">
    <style>
        @page {
            size: A4;
            margin: 0;
        }
        @media print {
            body {
                width: 210mm;
                height: 297mm;
            }
            .no-print {
                display: none !important;
            }
        }
    </style>
{% endblock %}

{% block content %}
    <div class="bg-white dark:bg-gray-900 text-gray-900 dark:text-white p-8">
        <div class="max-w-4xl mx-auto">
            <div class="flex flex-col items-start mb-8">
                <img src="{% static 'images/DiginusaLogo.png' %}" alt="Logo Perusahaan" class="w-40 mb-4">
                <h1 class="text-3xl font-bold">Layanan Teknisi</h1>
            </div>

            <hr class="my-8 border-1.5 border-black dark:border-white">

            <div class="space-y-4 mb-8">
                <p><span class="font-semibold">Nama Teknisi:</span> {{ kunjungan.teknisi.nama }}</p>
                <p><span class="font-semibold">Sekolah yang dikunjungi:</span></p>
                <ul class="list-disc pl-8">
                {% for sekolah in kunjungan.sekolah.all %}
                    <li>
                        <p>{{ sekolah.nama_sekolah }} ({{ sekolah.jenjang }})</p>
                    </li>
                {% endfor %}
                </ul>
                <p><span class="font-semibold">Tanggal:</span> {{ kunjungan.tanggal }}</p>
                <p><span class="font-semibold">Jenis Kegiatan:</span> {{ kunjungan.get_judul_display }}</p>
            </div>

            <hr class="my-8 border-1.5 border-black dark:border-white">

            <div class="mb-8">
                <h2 class="text-xl font-semibold mb-4">Kegiatan Layanan:</h2>
                <p class="whitespace-pre-line">{{ kunjungan.deskripsi }}</p>
            </div>

            <div class="mt-16 flex justify-end">
                {% if kunjungan.ttd %}
                    <div class="flex flex-col items-center justify-center max-w-[200px] w-full">
                        <img src="{{ kunjungan.ttd.url }}" alt="Tanda Tangan" class="mb-4 max-w-[200px]">
                        <hr class="w-full border-1 border-black dark:border-white mb-4">
                        <div class="flex flex-col items-center">
                            <p class="font-semibold text-center">{{ kunjungan.nama_kepsek_atau_guru }}</p>
                        </div>
                    </div>
                {% else %}
                    <div class="flex flex-col items-center justify-center max-w-xs w-full">
                        <p class="mb-4 italic">Tanda tangan tidak tersedia</p>
                        <p class="font-semibold">{{ kunjungan.nama_kepsek_atau_guru|default_if_none:"" }}</p>
                    </div>
                {% endif %}
            </div>

            <div class="mt-8 flex justify-center gap-4">
                <button class="no-print px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50" onclick="window.print()">Cetak</button>
                <button onclick="window.history.back()" class="no-print px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-opacity-50">Kembali</button>
            </div>
        </div>
    </div>
{% endblock %}